include(CMakeParseArguments)

#copy_replace_in_file(<filename> DESTINATION <dst> MATCH <match_string> REPLACE <replace replace_string>)
function(copy_replace_in_file)
    set(options)
    set(oneValueArgs DESTINATION MATCH REPLACE)
    set(multiValueArgs)
    cmake_parse_arguments(CP "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    file(READ "${ARGV0}" FILE_CONTENT)
    string(REPLACE ${CP_MATCH} ${CP_REPLACE} REPLACED_CONTENT ${FILE_CONTENT})
    file(WRITE "${DESTINATION}" ${REPLACED_CONTENT})
endfunction()
